package es.um.atica.sai.entities;
// Generated 15-jun-2021 9:48:31 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Intervencion generated by hbm2java
 */
@Entity
@Table( name = "INTERVENCION" )
@SequenceGenerator( name = "SEQ_INTERVENCION",	sequenceName = "SQ_INTERVENCION", initialValue = 0, allocationSize = 1 )
public class Intervencion implements java.io.Serializable {

	private static final long serialVersionUID = 8075901485707279349L;

	private Long cod;
	private Equipo equipo;
	private Date fecha;
	private String tipo;
	private BigDecimal precioBase;
	private String descripcion;

	public Intervencion() {}

	public Intervencion( Long cod, Equipo equipo, Date fecha, String tipo, BigDecimal precioBase,
			String descripcion ) {
		this.cod = cod;
		this.equipo = equipo;
		this.fecha = fecha;
		this.tipo = tipo;
		this.precioBase = precioBase;
		this.descripcion = descripcion;
	}

	@Id
	@GeneratedValue( strategy = GenerationType.SEQUENCE, generator = "SEQ_INTERVENCION" )
	@Column( name = "COD", unique = true, nullable = false, scale = 0 )
	public Long getCod() {
		return cod;
	}

	public void setCod( Long cod ) {
		this.cod = cod;
	}

	@ManyToOne( fetch = FetchType.EAGER )
	@JoinColumn( name = "COD_EQUIPO", nullable = false )
	public Equipo getEquipo() {
		return equipo;
	}

	public void setEquipo( Equipo equipo ) {
		this.equipo = equipo;
	}

	@Temporal( TemporalType.DATE )
	@Column( name = "FECHA", nullable = false, length = 7 )
	public Date getFecha() {
		return fecha;
	}

	public void setFecha( Date fecha ) {
		this.fecha = fecha;
	}

	@Column( name = "TIPO", nullable = false, length = 10 )
	public String getTipo() {
		return tipo;
	}

	public void setTipo( String tipo ) {
		this.tipo = tipo;
	}

	@Column( name = "PRECIO_BASE", nullable = false )
	public BigDecimal getPrecioBase() {
		return precioBase;
	}

	public void setPrecioBase( BigDecimal precioBase ) {
		this.precioBase = precioBase;
	}

	@Column( name = "DESCRIPCION", nullable = false, length = 4000 )
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion( String descripcion ) {
		this.descripcion = descripcion;
	}

}
