package es.um.atica.sai.entities;
// Generated 24-mar-2021 8:40:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProductoTipoCertificacion generated by hbm2java
 */
@Entity
@Table( name = "PRODUCTO_TIPO_CERTIFICACION", uniqueConstraints = @UniqueConstraint( columnNames = {
		"COD_PRODUCTO", "COD_TIPO_CERTIFICACION"
} ) )
@SequenceGenerator( name = "SQ_PRODUCTO_TIPO_CERTIFICACION",
					sequenceName = "SQ_PRODUCTO_TIPO_CERTIFICACION",
					initialValue = 0,
					allocationSize = 1 )

public class ProductoTipoCertificacion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 2965881829169533533L;
	private Long cod;
	private TipoCertificacion tipoCertificacion;
	private Producto producto;

	public ProductoTipoCertificacion() {}

	public ProductoTipoCertificacion( TipoCertificacion tipoCertificacion, Producto producto ) {
		this.tipoCertificacion = tipoCertificacion;
		this.producto = producto;
	}

	@Id
	@GeneratedValue( strategy = GenerationType.SEQUENCE, generator = "SQ_PRODUCTO_TIPO_CERTIFICACION" )
	@Column( name = "COD", unique = true, nullable = false, scale = 0 )
	public Long getCod() {
		return cod;
	}

	public void setCod( Long cod ) {
		this.cod = cod;
	}

	@ManyToOne( fetch = FetchType.EAGER )
	@JoinColumn( name = "COD_TIPO_CERTIFICACION", nullable = false )
	public TipoCertificacion getTipoCertificacion() {
		return tipoCertificacion;
	}

	public void setTipoCertificacion( TipoCertificacion tipoCertificacion ) {
		this.tipoCertificacion = tipoCertificacion;
	}

	@ManyToOne( fetch = FetchType.EAGER )
	@JoinColumn( name = "COD_PRODUCTO", nullable = false )
	public Producto getProducto() {
		return producto;
	}

	public void setProducto( Producto producto ) {
		this.producto = producto;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = ( prime * result ) + ( ( cod == null ) ? 0 : cod.hashCode() );
		return result;
	}

	@Override
	public boolean equals( Object obj ) {
		if ( this == obj ) {
			return true;
		}
		if ( !( obj instanceof ProductoTipoCertificacion ) ) {
			return false;
		}
		final ProductoTipoCertificacion other = ( ProductoTipoCertificacion ) obj;
		if ( getCod() == null ) {
			if ( other.getCod() != null ) {
				return false;
			}
		} else if ( !getCod().equals( other.getCod() ) ) {
			return false;
		}
		return true;
	}

}
