package es.um.atica.sai.entities;
// Generated 24-jun-2009 10:06:20 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;

/**
 * TarifaId generated by hbm2java
 */
@Embeddable
public class TarifaId implements java.io.Serializable {

	private static final long serialVersionUID = 1126634072055340950L;

	private Long cantidadInicial;
	private Long codProducto;
	private Long codTipoTarifa;

	public TarifaId() {
	}

	public TarifaId( Long cantidadInicial, Long codProducto, Long codTipoTarifa ) {
		this.cantidadInicial = cantidadInicial;
		this.codProducto = codProducto;
		this.codTipoTarifa = codTipoTarifa;
	}

	@Column(name = "CANTIDAD_INICIAL", nullable = false,precision = 19, scale = 0)
	@NotNull
	public Long getCantidadInicial() {
		return cantidadInicial;
	}
	
	public void setCantidadInicial( Long cantidadInicial ) {
		this.cantidadInicial = cantidadInicial;
	}

	@Column(name = "COD_PRODUCTO", nullable = false,precision = 19, scale = 0)
	@NotNull
	public Long getCodProducto() {
		return codProducto;
	}
	
	public void setCodProducto( Long codProducto ) {
		this.codProducto = codProducto;
	}

	@Column(name = "COD_TIPO_TARIFA", nullable = false, precision = 19, scale = 0)
	@NotNull
	public Long getCodTipoTarifa() {
		return codTipoTarifa;
	}
	
	public void setCodTipoTarifa( Long codTipoTarifa ) {
		this.codTipoTarifa = codTipoTarifa;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ( ( cantidadInicial == null ) ? 0 : cantidadInicial.hashCode() );
		result = prime * result + ( ( codProducto == null ) ? 0 : codProducto.hashCode() );
		result = prime * result + ( ( codTipoTarifa == null ) ? 0 : codTipoTarifa.hashCode() );
		return result;
	}

	@Override
	public boolean equals( Object obj ) {
		if ( this == obj )
			return true;
		if ( !( obj instanceof TarifaId ) )
			return false;
		TarifaId other = ( TarifaId ) obj;
		if ( cantidadInicial == null ) {
			if ( other.getCantidadInicial() != null )
				return false;
		} else if ( !cantidadInicial.equals( other.getCantidadInicial() ) )
			return false;
		if ( codProducto == null ) {
			if ( other.getCodProducto() != null )
				return false;
		} else if ( !codProducto.equals( other.getCodProducto()))
			return false;
		if ( codTipoTarifa == null ) {
			if ( other.getCodTipoTarifa() != null )
				return false;
		} else if ( !codTipoTarifa.equals( other.getCodTipoTarifa() ) )
			return false;
		return true;
	}


	
}
